import Head from 'next/head'

export default function Page() {
  return (
    <>
      <Head>
        <title>Archdiocesan Nourishment Center</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
        <div className='min-h-[500px]'>
          About Us
        </div>
      
    </>
  )
}
